spring.application.name=payflowAPI
#spring.data.mongodb.uri=mongodb://localhost:27017/payflow
spring.data.mongodb.uri=mongodb+srv://payflow:payflow1234@cluster0.p3yye8g.mongodb.net/payflow?retryWrites=true&w=majority
logging.level.org.springframework.data.mongodb=DEBUG
#spring.data.mongodb.database=payflow
twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=+18208007256
twilio.verify.service.sid=VAb58538c177ecd0e0a8465f674ed234fd
spring.data.mongodb.host=INVALID_HOST
spring.data.mongodb.auto-index-creation=true

#mongodb+srv://payflow:payflow1234@cluster0.p3yye8g.mongodb.net/?appName=Cluster0
